### ISSUE TITLE
Setwinner not working

### ISSUE THREAD

**Issue by web3devz** [lucasvanmol/algobets#1]
setwinner not working

**Comment by lucasvanmol** [comment]
What command specifically are you trying to run? I'm assuming you're using the python CLI, so could you also run ` python .\admin.py info app_id` with the `app_id` of the dapp you're trying to set the winner for?

**Comment by web3devz** [comment]
[image: image.png]
this is the error

**Comment by rukmani887799** [comment]
PS C:\Users\sambi\Downloads\sa23sa\admin> python ./admin.py setwinner my_private_key 78129813 Rajasthan
Updating application with args: ['winner', 'Rajasthan']
Traceback (most recent call last):
  File "C:\Users\sambi\AppData\Local\Programs\Python\Python310\lib\site-packages\algosdk\v2client\algod.py", line 78, in algod_request
    resp = urlopen(req)
  File "C:\Users\sambi\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\sambi\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\sambi\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\sambi\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Users\sambi\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\sambi\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sambi\Downloads\sa23sa\admin\admin.py", line 220, in <module>
    args.func(args)
  File "C:\Users\sambi\Downloads\sa23sa\admin\admin.py", line 168, in arg_setwinner
    set_winner(pk, args.app_id, args.team_name)
  File "C:\Users\sambi\Downloads\sa23sa\admin\admin.py", line 88, in set_winner
    transaction_response = utils.call_application(
  File "C:\Users\sambi\Downloads\sa23sa\admin\utils.py", line 74, in call_application
    tx_id = client.send_transaction(signed_txn)
  File "C:\Users\sambi\AppData\Local\Programs\Python\Python310\lib\site-packages\algosdk\v2client\algod.py", line 210, in send_transaction
    return self.send_raw_transaction(
  File "C:\Users\sambi\AppData\Local\Programs\Python\Python310\lib\site-packages\algosdk\v2client\algod.py", line 233, in send_raw_transaction
    return self.algod_request("POST", req, data=txn, **kwargs)["txId"]
  File "C:\Users\sambi\AppData\Local\Programs\Python\Python310\lib\site-packages\algosdk\v2client\algod.py", line 85, in algod_request
    raise error.AlgodHTTPError(e, code)
algosdk.error.AlgodHTTPError: TransactionPool.Remember: transaction G4EEP5BA4KCAG3SQ6PYDEYALKOBVB4GDETKZLSHV5L5J7NNDN2UA: logic eval error: assert failed pc=360. Details: pc=360, opcodes=app_global_get
<=
assert

**Comment by lucasvanmol** [comment]
Looks like the smart contract is rejecting your app call which may be for a number of reasons:

- the winner can only be set in between the `LimitDate` and `EndDate` parameters, so you may be too late or too early depending on what you set these parameters as
- the winner you set (e.g. `Rajasthan`) does not correspond to a team name set in the contract
- the private key you used for the call is not the private key of the address that originally created the smart contract

You can check the contract's `LimitDate`, `EndDate`, and team names using `python ./admin.py info 78129813` in your case.

**Comment by lucasvanmol** [comment]
After guessing you might be running on the testnet, I've run the command for you:
```
> python .\admin.py info 78129813
{'id': '78129813', 'Team2': 'Rajasthan', 'EndDate': 1647377418, 'LimitDate': 1647377418, 'Team1Total': 1000000, 'Team2Total': 3000000, 'Escrow': 'YZSASDENAIOWOPREZG3EDXO5NSRVXY4O6H2HO7MQZMPZW6JN5RJ5FRCMJY', 'Winner': '', 'Team1': 'Pune'}
```

Looks like your `EndDate` and `LimitDate` are the both set to the same value (corresponding to some time yesterday) which is the problem. Using setwinner can only be done between these two dates (see the [readme](https://github.com/lucasvanmol/algobets/tree/main/teal) for more information).

**Comment by web3devz** [comment]
Awesome, thanks!
smartcontract is not in github repo i think
